kind: PersistentVolume
apiVersion: v1
metadata: 
  name: my-pv
  labels: 
    type: local      #identification 
spec:
  hostPath: 
    path: /my-pv-data-onvm    #will create a direcoty on node disk name my-pv-data-onvm    
  capacity: 
     storage: 2Gi        #you can specify what ever you want but it should be less thanor equal to available node disk space
  accessModes: 
   - ReadWriteMany # ReadOnlyMany / ReadWriteMany The number of nodes that can write the data to volume

